goog.module('org.pepstock.charba.client.datalabels.LabelItem');

goog.require('java.lang.Boolean');
goog.require('java.lang.Double');
goog.require('java.lang.Integer');
goog.require('java.lang.String');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.callbacks.ColorCallback');
goog.require('org.pepstock.charba.client.callbacks.FontCallback');
goog.require('org.pepstock.charba.client.callbacks.NativeCallback.$Overlay');
goog.require('org.pepstock.charba.client.callbacks.OffsetCallback');
goog.require('org.pepstock.charba.client.callbacks.PaddingCallback');
goog.require('org.pepstock.charba.client.callbacks.RadiusCallback');
goog.require('org.pepstock.charba.client.callbacks.RotationCallback');
goog.require('org.pepstock.charba.client.callbacks.ScriptableUtils');
goog.require('org.pepstock.charba.client.callbacks.TextAlignCallback');
goog.require('org.pepstock.charba.client.callbacks.WidthCallback');
goog.require('org.pepstock.charba.client.colors.ColorBuilder');
goog.require('org.pepstock.charba.client.colors.IsColor');
goog.require('org.pepstock.charba.client.commons.CallbackPropertyHandler');
goog.require('org.pepstock.charba.client.commons.CallbackProxy.$Overlay');
goog.require('org.pepstock.charba.client.commons.Checker');
goog.require('org.pepstock.charba.client.commons.JsHelper');
goog.require('org.pepstock.charba.client.commons.NativeObject.$Overlay');
goog.require('org.pepstock.charba.client.commons.ObjectType');
goog.require('org.pepstock.charba.client.datalabels.DataLabelsContext');
goog.require('org.pepstock.charba.client.datalabels.DataLabelsOptions');
goog.require('org.pepstock.charba.client.datalabels.DataLabelsPlugin');
goog.require('org.pepstock.charba.client.datalabels.Font');
goog.require('org.pepstock.charba.client.datalabels.IsDefaultDataLabelsItem');
goog.require('org.pepstock.charba.client.datalabels.LabelItem.Property');
goog.require('org.pepstock.charba.client.datalabels.Listeners');
goog.require('org.pepstock.charba.client.datalabels.Padding');
goog.require('org.pepstock.charba.client.datalabels.callbacks.AlignCallback');
goog.require('org.pepstock.charba.client.datalabels.callbacks.AnchorCallback');
goog.require('org.pepstock.charba.client.datalabels.callbacks.ClampCallback');
goog.require('org.pepstock.charba.client.datalabels.callbacks.ClipCallback');
goog.require('org.pepstock.charba.client.datalabels.callbacks.DisplayCallback');
goog.require('org.pepstock.charba.client.datalabels.callbacks.FormatterCallback');
goog.require('org.pepstock.charba.client.datalabels.callbacks.OpacityCallback');
goog.require('org.pepstock.charba.client.datalabels.callbacks.TextShadowBlurCallback');
goog.require('org.pepstock.charba.client.datalabels.enums.Align');
goog.require('org.pepstock.charba.client.datalabels.enums.Anchor');
goog.require('org.pepstock.charba.client.datalabels.events.AbstractEventHandler');
goog.require('org.pepstock.charba.client.enums.Display');
goog.require('org.pepstock.charba.client.enums.TextAlign');
goog.require('org.pepstock.charba.client.items.DataItem');
goog.require('org.pepstock.charba.client.options.IsScriptableFontProvider');
goog.require('org.pepstock.charba.client.options.IsScriptablePaddingProvider');
goog.require('org.pepstock.charba.client.plugins.AbstractPluginOptions');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');

const LabelItem = goog.require('org.pepstock.charba.client.datalabels.LabelItem$impl');
exports = LabelItem;

