goog.module('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelector');

goog.require('java.lang.Boolean');
goog.require('java.lang.String');
goog.require('java.util.HashMap');
goog.require('java.util.Map');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.ChartType');
goog.require('org.pepstock.charba.client.IsChart');
goog.require('org.pepstock.charba.client.ScaleType');
goog.require('org.pepstock.charba.client.callbacks.NativeCallback.$Overlay');
goog.require('org.pepstock.charba.client.commons.Checker');
goog.require('org.pepstock.charba.client.configuration.BarOptions');
goog.require('org.pepstock.charba.client.configuration.LineOptions');
goog.require('org.pepstock.charba.client.data.BarDataset');
goog.require('org.pepstock.charba.client.data.Dataset');
goog.require('org.pepstock.charba.client.data.LineDataset');
goog.require('org.pepstock.charba.client.dom.BaseNativeEvent.$Overlay');
goog.require('org.pepstock.charba.client.dom.BaseStyleProperties.$Overlay');
goog.require('org.pepstock.charba.client.dom.DOMBuilder');
goog.require('org.pepstock.charba.client.dom.elements.Canvas.$Overlay');
goog.require('org.pepstock.charba.client.dom.enums.CursorType');
goog.require('org.pepstock.charba.client.enums.Event');
goog.require('org.pepstock.charba.client.enums.IndexAxis');
goog.require('org.pepstock.charba.client.events.DatasetRangeCleanSelectionEvent');
goog.require('org.pepstock.charba.client.events.HandlerRegistration');
goog.require('org.pepstock.charba.client.events.LegendClickEvent');
goog.require('org.pepstock.charba.client.impl.callbacks.AtLeastOneDatasetHandler');
goog.require('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelectorDefaultOptions');
goog.require('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelectorOptions');
goog.require('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelectorOptionsFactory');
goog.require('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelectorOptionsFactory.DatasetsItemsSelectorDefaultsOptionsFactory');
goog.require('org.pepstock.charba.client.impl.plugins.SelectionCleaner');
goog.require('org.pepstock.charba.client.impl.plugins.SelectionHandler');
goog.require('org.pepstock.charba.client.impl.plugins.SelectionStatus');
goog.require('org.pepstock.charba.client.items.PluginEventArgument');
goog.require('org.pepstock.charba.client.plugins.AbstractPlugin');
goog.require('org.pepstock.charba.client.resources.ResourceName');
goog.require('org.pepstock.charba.client.utils.Utilities');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');

const DatasetsItemsSelector = goog.require('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelector$impl');
exports = DatasetsItemsSelector;

