goog.module('org.pepstock.charba.client.impl.plugins.HtmlLegendGenerator');

goog.require('java.lang.Double');
goog.require('java.lang.Object');
goog.require('java.lang.String');
goog.require('java.util.Collections');
goog.require('java.util.Comparator');
goog.require('java.util.LinkedList');
goog.require('java.util.List');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.Defaults');
goog.require('org.pepstock.charba.client.IsChart');
goog.require('org.pepstock.charba.client.callbacks.HtmlLegendItemCallback');
goog.require('org.pepstock.charba.client.callbacks.HtmlLegendTitleCallback');
goog.require('org.pepstock.charba.client.colors.tiles.TilesFactory');
goog.require('org.pepstock.charba.client.commons.Checker');
goog.require('org.pepstock.charba.client.commons.Constants');
goog.require('org.pepstock.charba.client.configuration.Legend');
goog.require('org.pepstock.charba.client.configuration.LegendTitle');
goog.require('org.pepstock.charba.client.dom.BaseStyleProperties.$Overlay');
goog.require('org.pepstock.charba.client.dom.DOMBuilder');
goog.require('org.pepstock.charba.client.dom.elements.Canvas.$Overlay');
goog.require('org.pepstock.charba.client.dom.elements.Context2dItem.$Overlay');
goog.require('org.pepstock.charba.client.dom.elements.Div.$Overlay');
goog.require('org.pepstock.charba.client.dom.elements.Table.$Overlay');
goog.require('org.pepstock.charba.client.dom.elements.TableCell.$Overlay');
goog.require('org.pepstock.charba.client.dom.enums.BorderStyle');
goog.require('org.pepstock.charba.client.dom.enums.Display');
goog.require('org.pepstock.charba.client.dom.enums.Repetition');
goog.require('org.pepstock.charba.client.dom.enums.TextBaseline');
goog.require('org.pepstock.charba.client.dom.enums.TextDecoration');
goog.require('org.pepstock.charba.client.dom.enums.Unit');
goog.require('org.pepstock.charba.client.dom.safehtml.SafeHtml');
goog.require('org.pepstock.charba.client.dom.safehtml.SafeHtmlBuilder');
goog.require('org.pepstock.charba.client.enums.PointStyleType');
goog.require('org.pepstock.charba.client.enums.TextAlign');
goog.require('org.pepstock.charba.client.enums.TextDirection');
goog.require('org.pepstock.charba.client.impl.plugins.HtmlLegend');
goog.require('org.pepstock.charba.client.impl.plugins.HtmlLegendId');
goog.require('org.pepstock.charba.client.impl.plugins.HtmlLegendItem');
goog.require('org.pepstock.charba.client.impl.plugins.HtmlLegendOptions');
goog.require('org.pepstock.charba.client.impl.plugins.HtmlLegendTextGenerator');
goog.require('org.pepstock.charba.client.items.DatasetElement');
goog.require('org.pepstock.charba.client.items.DatasetElementOptions');
goog.require('org.pepstock.charba.client.items.LegendItem');
goog.require('org.pepstock.charba.client.items.LegendLabelItem');
goog.require('org.pepstock.charba.client.items.Undefined');
goog.require('org.pepstock.charba.client.utils.Utilities');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');
goog.require('vmbootstrap.Primitives');

const HtmlLegendGenerator = goog.require('org.pepstock.charba.client.impl.plugins.HtmlLegendGenerator$impl');
exports = HtmlLegendGenerator;

