goog.module('org.pepstock.charba.client.defaults.globals.AbstractDefaultOptions');

goog.require('java.lang.Object');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.commons.Checker');
goog.require('org.pepstock.charba.client.defaults.IsDefaultAnimation');
goog.require('org.pepstock.charba.client.defaults.IsDefaultAnimations');
goog.require('org.pepstock.charba.client.defaults.IsDefaultDatasets');
goog.require('org.pepstock.charba.client.defaults.IsDefaultDecimation');
goog.require('org.pepstock.charba.client.defaults.IsDefaultElements');
goog.require('org.pepstock.charba.client.defaults.IsDefaultFiller');
goog.require('org.pepstock.charba.client.defaults.IsDefaultFont');
goog.require('org.pepstock.charba.client.defaults.IsDefaultInteraction');
goog.require('org.pepstock.charba.client.defaults.IsDefaultLayout');
goog.require('org.pepstock.charba.client.defaults.IsDefaultLegend');
goog.require('org.pepstock.charba.client.defaults.IsDefaultOptions');
goog.require('org.pepstock.charba.client.defaults.IsDefaultPlugins');
goog.require('org.pepstock.charba.client.defaults.IsDefaultTitle');
goog.require('org.pepstock.charba.client.defaults.IsDefaultTooltips');
goog.require('org.pepstock.charba.client.defaults.IsDefaultTransitions');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartAnimation');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartAnimations');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartDatasets');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartDecimation');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartElements');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartFiller');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartFont');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartHover');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartInteraction');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartLayout');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartLegend');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartPlugins');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartTitle');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartTooltips');
goog.require('org.pepstock.charba.client.defaults.chart.DefaultChartTransitions');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultAnimation');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultAnimations');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultDatasets');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultDecimation');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultElements');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultFiller');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultFont');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultHover');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultInteraction');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultLayout');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultLegend');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultPlugins');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultRoutedFont');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultTitle');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultTooltips');
goog.require('org.pepstock.charba.client.defaults.globals.DefaultTransitions');

const AbstractDefaultOptions = goog.require('org.pepstock.charba.client.defaults.globals.AbstractDefaultOptions$impl');
exports = AbstractDefaultOptions;

