goog.module('org.pepstock.charba.client.configuration.Axis');

goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.Defaults');
goog.require('org.pepstock.charba.client.IsChart');
goog.require('org.pepstock.charba.client.ScaleType');
goog.require('org.pepstock.charba.client.callbacks.AxisBuildTicksCallback');
goog.require('org.pepstock.charba.client.callbacks.AxisCalculateTickRotationCallback');
goog.require('org.pepstock.charba.client.callbacks.AxisDataLimitsCallback');
goog.require('org.pepstock.charba.client.callbacks.AxisDimensionsCallback');
goog.require('org.pepstock.charba.client.callbacks.AxisFitCallback');
goog.require('org.pepstock.charba.client.callbacks.AxisTickToLabelConversionCallback');
goog.require('org.pepstock.charba.client.callbacks.AxisUpdateCallback');
goog.require('org.pepstock.charba.client.callbacks.CallbackFunctionContext.$Overlay');
goog.require('org.pepstock.charba.client.callbacks.ScaleContext');
goog.require('org.pepstock.charba.client.colors.IsColor');
goog.require('org.pepstock.charba.client.commons.AbstractNode');
goog.require('org.pepstock.charba.client.commons.CallbackProxy.$Overlay');
goog.require('org.pepstock.charba.client.commons.JsHelper');
goog.require('org.pepstock.charba.client.commons.Key');
goog.require('org.pepstock.charba.client.commons.NativeObject.$Overlay');
goog.require('org.pepstock.charba.client.configuration.Axis.Property');
goog.require('org.pepstock.charba.client.configuration.ConfigurationContainer');
goog.require('org.pepstock.charba.client.configuration.ConfigurationEnvelop');
goog.require('org.pepstock.charba.client.configuration.ConfigurationOptions');
goog.require('org.pepstock.charba.client.defaults.IsDefaultScale');
goog.require('org.pepstock.charba.client.enums.AxisKind');
goog.require('org.pepstock.charba.client.enums.AxisType');
goog.require('org.pepstock.charba.client.enums.Display');
goog.require('org.pepstock.charba.client.items.AxisItem');
goog.require('org.pepstock.charba.client.options.ExtendedScale');
goog.require('org.pepstock.charba.client.options.IsScaleId');
goog.require('org.pepstock.charba.client.options.Scale');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');

const Axis = goog.require('org.pepstock.charba.client.configuration.Axis$impl');
exports = Axis;

