goog.module('org.pepstock.charba.client.configuration.Line');

goog.require('java.lang.Double');
goog.require('java.lang.Integer');
goog.require('java.util.List');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.callbacks.BorderDashCallback');
goog.require('org.pepstock.charba.client.callbacks.BorderDashOffsetCallback');
goog.require('org.pepstock.charba.client.callbacks.CapStyleCallback');
goog.require('org.pepstock.charba.client.callbacks.CubicInterpolationModeCallback');
goog.require('org.pepstock.charba.client.callbacks.DatasetContext');
goog.require('org.pepstock.charba.client.callbacks.FillCallback');
goog.require('org.pepstock.charba.client.callbacks.JoinStyleCallback');
goog.require('org.pepstock.charba.client.callbacks.NativeCallback.$Overlay');
goog.require('org.pepstock.charba.client.callbacks.ScriptableUtils');
goog.require('org.pepstock.charba.client.callbacks.SteppedCallback');
goog.require('org.pepstock.charba.client.commons.Array.$Overlay');
goog.require('org.pepstock.charba.client.commons.ArrayInteger.$Overlay');
goog.require('org.pepstock.charba.client.commons.CallbackProxy.$Overlay');
goog.require('org.pepstock.charba.client.commons.Checker');
goog.require('org.pepstock.charba.client.commons.JsHelper');
goog.require('org.pepstock.charba.client.commons.Key');
goog.require('org.pepstock.charba.client.commons.NativeObject.$Overlay');
goog.require('org.pepstock.charba.client.configuration.AbstractConfigurationElement');
goog.require('org.pepstock.charba.client.configuration.ConfigurationOptions');
goog.require('org.pepstock.charba.client.configuration.Line.Property');
goog.require('org.pepstock.charba.client.defaults.IsDefaultLine');
goog.require('org.pepstock.charba.client.enums.CapStyle');
goog.require('org.pepstock.charba.client.enums.CubicInterpolationMode');
goog.require('org.pepstock.charba.client.enums.IsFill');
goog.require('org.pepstock.charba.client.enums.JoinStyle');
goog.require('org.pepstock.charba.client.enums.Stepped');
goog.require('org.pepstock.charba.client.options.AbstractElement');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');

const Line = goog.require('org.pepstock.charba.client.configuration.Line$impl');
exports = Line;

