goog.module('org.pepstock.charba.client.configuration.Title');

goog.require('java.lang.Boolean');
goog.require('java.lang.String');
goog.require('java.util.LinkedList');
goog.require('java.util.List');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.callbacks.CallbackFunctionContext.$Overlay');
goog.require('org.pepstock.charba.client.callbacks.ChartContext');
goog.require('org.pepstock.charba.client.callbacks.ColorCallback');
goog.require('org.pepstock.charba.client.callbacks.DisplayCallback');
goog.require('org.pepstock.charba.client.callbacks.ElementAlignCallback');
goog.require('org.pepstock.charba.client.callbacks.FontCallback');
goog.require('org.pepstock.charba.client.callbacks.FullSizeCallback');
goog.require('org.pepstock.charba.client.callbacks.PaddingCallback');
goog.require('org.pepstock.charba.client.callbacks.PositionCallback');
goog.require('org.pepstock.charba.client.callbacks.ScriptableUtils');
goog.require('org.pepstock.charba.client.callbacks.TextCallback');
goog.require('org.pepstock.charba.client.colors.ColorBuilder');
goog.require('org.pepstock.charba.client.colors.IsColor');
goog.require('org.pepstock.charba.client.commons.ArrayString.$Overlay');
goog.require('org.pepstock.charba.client.commons.CallbackProxy.$Overlay');
goog.require('org.pepstock.charba.client.commons.JsHelper');
goog.require('org.pepstock.charba.client.commons.NativeObject.$Overlay');
goog.require('org.pepstock.charba.client.configuration.AbstractDynamicConfiguration.IsProvider');
goog.require('org.pepstock.charba.client.configuration.ConfigurationOptions');
goog.require('org.pepstock.charba.client.configuration.ConfigurationOptionsContainer');
goog.require('org.pepstock.charba.client.configuration.Font');
goog.require('org.pepstock.charba.client.configuration.Padding');
goog.require('org.pepstock.charba.client.configuration.Title.Property');
goog.require('org.pepstock.charba.client.enums.ElementAlign');
goog.require('org.pepstock.charba.client.enums.Position');
goog.require('org.pepstock.charba.client.options.ExtendedOptions');
goog.require('org.pepstock.charba.client.options.IsScriptableFontProvider');
goog.require('org.pepstock.charba.client.options.IsScriptablePaddingProvider');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');

const Title = goog.require('org.pepstock.charba.client.configuration.Title$impl');
exports = Title;

