goog.module('org.pepstock.charba.client.options.AnimationCollection');

goog.require('java.lang.Boolean');
goog.require('java.lang.Double');
goog.require('java.lang.String');
goog.require('java.util.LinkedList');
goog.require('java.util.List');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.callbacks.DatasetContext');
goog.require('org.pepstock.charba.client.callbacks.FromCallback');
goog.require('org.pepstock.charba.client.callbacks.NativeCallback.$Overlay');
goog.require('org.pepstock.charba.client.callbacks.Scriptable');
goog.require('org.pepstock.charba.client.callbacks.ScriptableUtils');
goog.require('org.pepstock.charba.client.callbacks.ToCallback');
goog.require('org.pepstock.charba.client.colors.ColorBuilder');
goog.require('org.pepstock.charba.client.colors.IsColor');
goog.require('org.pepstock.charba.client.commons.ArrayString.$Overlay');
goog.require('org.pepstock.charba.client.commons.CallbackPropertyHandler');
goog.require('org.pepstock.charba.client.commons.CallbackProxy.$Overlay');
goog.require('org.pepstock.charba.client.commons.HasCallbackScope');
goog.require('org.pepstock.charba.client.commons.JsHelper');
goog.require('org.pepstock.charba.client.commons.Key');
goog.require('org.pepstock.charba.client.commons.NativeObject.$Overlay');
goog.require('org.pepstock.charba.client.commons.ObjectType');
goog.require('org.pepstock.charba.client.defaults.IsDefaultAnimationCollection');
goog.require('org.pepstock.charba.client.enums.AnimationType');
goog.require('org.pepstock.charba.client.enums.DefaultAnimationPropertyKey');
goog.require('org.pepstock.charba.client.options.AbstractAnimation');
goog.require('org.pepstock.charba.client.options.AnimationCollection.Property');
goog.require('org.pepstock.charba.client.options.AnimationCollectionKey');
goog.require('org.pepstock.charba.client.options.AnimationPropertyKey');
goog.require('org.pepstock.charba.client.options.Animations');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');

const AnimationCollection = goog.require('org.pepstock.charba.client.options.AnimationCollection$impl');
exports = AnimationCollection;

