goog.module('org.pepstock.charba.client.options.Options');

goog.require('java.lang.String');
goog.require('java.util.List');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.colors.ColorBuilder');
goog.require('org.pepstock.charba.client.colors.IsColor');
goog.require('org.pepstock.charba.client.commons.ArrayEnumList');
goog.require('org.pepstock.charba.client.commons.ArrayListHelper');
goog.require('org.pepstock.charba.client.commons.ArrayString.$Overlay');
goog.require('org.pepstock.charba.client.commons.Checker');
goog.require('org.pepstock.charba.client.commons.Id');
goog.require('org.pepstock.charba.client.commons.NativeObject.$Overlay');
goog.require('org.pepstock.charba.client.commons.ObjectType');
goog.require('org.pepstock.charba.client.defaults.IsDefaultOptions');
goog.require('org.pepstock.charba.client.enums.DefaultPluginId');
goog.require('org.pepstock.charba.client.enums.Event');
goog.require('org.pepstock.charba.client.enums.IndexAxis');
goog.require('org.pepstock.charba.client.intl.CLocale');
goog.require('org.pepstock.charba.client.intl.CLocaleBuilder');
goog.require('org.pepstock.charba.client.items.Undefined');
goog.require('org.pepstock.charba.client.options.AbstractModel');
goog.require('org.pepstock.charba.client.options.Animation');
goog.require('org.pepstock.charba.client.options.AnimationContainer');
goog.require('org.pepstock.charba.client.options.Animations');
goog.require('org.pepstock.charba.client.options.Datasets');
goog.require('org.pepstock.charba.client.options.Decimation');
goog.require('org.pepstock.charba.client.options.Elements');
goog.require('org.pepstock.charba.client.options.Filler');
goog.require('org.pepstock.charba.client.options.Font');
goog.require('org.pepstock.charba.client.options.HasAnimationOptions');
goog.require('org.pepstock.charba.client.options.HasSpanGaps');
goog.require('org.pepstock.charba.client.options.Hover');
goog.require('org.pepstock.charba.client.options.Interaction');
goog.require('org.pepstock.charba.client.options.Layout');
goog.require('org.pepstock.charba.client.options.Legend');
goog.require('org.pepstock.charba.client.options.Options.CommonProperty');
goog.require('org.pepstock.charba.client.options.Options.Property');
goog.require('org.pepstock.charba.client.options.Plugins');
goog.require('org.pepstock.charba.client.options.SpanGapHandler');
goog.require('org.pepstock.charba.client.options.Title');
goog.require('org.pepstock.charba.client.options.Tooltips');
goog.require('org.pepstock.charba.client.options.Transitions');
goog.require('vmbootstrap.Casts');

const Options = goog.require('org.pepstock.charba.client.options.Options$impl');
exports = Options;

