goog.module('org.pepstock.charba.client.options.Tooltips');

goog.require('java.lang.IllegalArgumentException');
goog.require('java.lang.String');
goog.require('java.util.List');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.colors.ColorBuilder');
goog.require('org.pepstock.charba.client.colors.IsColor');
goog.require('org.pepstock.charba.client.commons.ArrayEnumList');
goog.require('org.pepstock.charba.client.commons.ArrayListHelper');
goog.require('org.pepstock.charba.client.commons.ArrayString.$Overlay');
goog.require('org.pepstock.charba.client.commons.Checker');
goog.require('org.pepstock.charba.client.commons.HasCallbackScope');
goog.require('org.pepstock.charba.client.commons.Key');
goog.require('org.pepstock.charba.client.commons.NativeObject.$Overlay');
goog.require('org.pepstock.charba.client.defaults.IsDefaultTooltips');
goog.require('org.pepstock.charba.client.enums.Event');
goog.require('org.pepstock.charba.client.enums.InteractionMode');
goog.require('org.pepstock.charba.client.enums.IsTooltipPosition');
goog.require('org.pepstock.charba.client.enums.TextAlign');
goog.require('org.pepstock.charba.client.enums.TextDirection');
goog.require('org.pepstock.charba.client.enums.TooltipAlign');
goog.require('org.pepstock.charba.client.enums.TooltipPosition');
goog.require('org.pepstock.charba.client.options.AbstractInteraction');
goog.require('org.pepstock.charba.client.options.Animation');
goog.require('org.pepstock.charba.client.options.AnimationContainer');
goog.require('org.pepstock.charba.client.options.Animations');
goog.require('org.pepstock.charba.client.options.BoxHandler');
goog.require('org.pepstock.charba.client.options.Font');
goog.require('org.pepstock.charba.client.options.HasAnimationOptions');
goog.require('org.pepstock.charba.client.options.HasBox');
goog.require('org.pepstock.charba.client.options.HasTextDirection');
goog.require('org.pepstock.charba.client.options.Padding');
goog.require('org.pepstock.charba.client.options.Plugins');
goog.require('org.pepstock.charba.client.options.TextDirectionHandler');
goog.require('org.pepstock.charba.client.options.Tooltips.Property');
goog.require('org.pepstock.charba.client.options.TooltipsCallbacks');
goog.require('org.pepstock.charba.client.options.Transitions');
goog.require('org.pepstock.charba.client.positioner.Positioner');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Exceptions');

const Tooltips = goog.require('org.pepstock.charba.client.options.Tooltips$impl');
exports = Tooltips;

