goog.module('org.pepstock.charba.showcase.j2cl.cases.plugins.ColorSchemeBubbleCase');

goog.require('elemental2.dom.CSSProperties.MarginRightUnionType.$Overlay');
goog.require('elemental2.dom.CSSProperties.WidthUnionType.$Overlay');
goog.require('elemental2.dom.Document.$Overlay');
goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLImageElement.$Overlay');
goog.require('elemental2.dom.HTMLInputElement.$Overlay');
goog.require('elemental2.dom.HTMLLabelElement.$Overlay');
goog.require('elemental2.dom.HTMLOptionElement.$Overlay');
goog.require('elemental2.dom.HTMLSelectElement.$Overlay');
goog.require('elemental2.dom.HTMLTableCellElement.$Overlay');
goog.require('elemental2.dom.HTMLTableElement.$Overlay');
goog.require('elemental2.dom.HTMLTableRowElement.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Math');
goog.require('java.lang.String');
goog.require('java.util.Random');
goog.require('jsinterop.base.JsArrayLike.$Overlay');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.BubbleChart');
goog.require('org.pepstock.charba.client.commons.Key');
goog.require('org.pepstock.charba.client.data.BubbleDataset');
goog.require('org.pepstock.charba.client.data.DataPoint');
goog.require('org.pepstock.charba.client.data.Dataset');
goog.require('org.pepstock.charba.client.dom.IsCastable.$Overlay');
goog.require('org.pepstock.charba.client.impl.plugins.ColorSchemes');
goog.require('org.pepstock.charba.client.impl.plugins.ColorSchemesOptions');
goog.require('org.pepstock.charba.client.impl.plugins.enums.BrewerScheme');
goog.require('org.pepstock.charba.client.impl.plugins.enums.GoogleChartScheme');
goog.require('org.pepstock.charba.client.impl.plugins.enums.GwtMaterialScheme');
goog.require('org.pepstock.charba.client.impl.plugins.enums.OfficeScheme');
goog.require('org.pepstock.charba.client.impl.plugins.enums.SchemeScope');
goog.require('org.pepstock.charba.client.impl.plugins.enums.TableauScheme');
goog.require('org.pepstock.charba.showcase.j2cl.cases.commons.BaseComposite');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Objects');
goog.require('vmbootstrap.Primitives');
goog.require('vmbootstrap.primitives.$int');

const ColorSchemeBubbleCase = goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.ColorSchemeBubbleCase$impl');
exports = ColorSchemeBubbleCase;

