goog.module('org.pepstock.charba.showcase.j2cl.cases.plugins.DatasetItemsSelectorBubbleCase');

goog.require('elemental2.dom.CSSProperties.MarginRightUnionType.$Overlay');
goog.require('elemental2.dom.CSSProperties.WidthUnionType.$Overlay');
goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLImageElement.$Overlay');
goog.require('elemental2.dom.HTMLTableCellElement.$Overlay');
goog.require('elemental2.dom.HTMLTableElement.$Overlay');
goog.require('elemental2.dom.HTMLTableRowElement.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.Math');
goog.require('java.lang.String');
goog.require('java.util.Random');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.BubbleChart');
goog.require('org.pepstock.charba.client.Defaults');
goog.require('org.pepstock.charba.client.colors.HtmlColor');
goog.require('org.pepstock.charba.client.data.BubbleDataset');
goog.require('org.pepstock.charba.client.data.DataPoint');
goog.require('org.pepstock.charba.client.data.Dataset');
goog.require('org.pepstock.charba.client.dom.IsCastable.$Overlay');
goog.require('org.pepstock.charba.client.events.DatasetRangeCleanSelectionEvent');
goog.require('org.pepstock.charba.client.events.DatasetRangeSelectionEvent');
goog.require('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelector');
goog.require('org.pepstock.charba.client.impl.plugins.DatasetsItemsSelectorOptions');
goog.require('org.pepstock.charba.showcase.j2cl.cases.commons.BaseComposite');
goog.require('org.pepstock.charba.showcase.j2cl.cases.commons.LogView');
goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.DatasetItemsSelectorBubbleCase.$1');
goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.DatasetItemsSelectorBubbleCase.$2');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Primitives');
goog.require('vmbootstrap.primitives.$int');

const DatasetItemsSelectorBubbleCase = goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.DatasetItemsSelectorBubbleCase$impl');
exports = DatasetItemsSelectorBubbleCase;

