goog.module('org.pepstock.charba.showcase.j2cl.cases.plugins.PointerLineCase');

goog.require('elemental2.dom.CSSProperties.MarginRightUnionType.$Overlay');
goog.require('elemental2.dom.CSSProperties.WidthUnionType.$Overlay');
goog.require('elemental2.dom.Document.$Overlay');
goog.require('elemental2.dom.DomGlobal.$Overlay');
goog.require('elemental2.dom.Event.$Overlay');
goog.require('elemental2.dom.HTMLButtonElement.$Overlay');
goog.require('elemental2.dom.HTMLElement.$Overlay');
goog.require('elemental2.dom.HTMLImageElement.$Overlay');
goog.require('elemental2.dom.HTMLInputElement.$Overlay');
goog.require('elemental2.dom.HTMLLabelElement.$Overlay');
goog.require('elemental2.dom.HTMLOptionElement.$Overlay');
goog.require('elemental2.dom.HTMLSelectElement.$Overlay');
goog.require('elemental2.dom.HTMLTableCellElement.$Overlay');
goog.require('elemental2.dom.HTMLTableElement.$Overlay');
goog.require('elemental2.dom.HTMLTableRowElement.$Overlay');
goog.require('elemental2.dom.Node.$Overlay');
goog.require('java.lang.String');
goog.require('java.util.LinkedList');
goog.require('java.util.List');
goog.require('jsinterop.base.JsArrayLike.$Overlay');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.LineChart');
goog.require('org.pepstock.charba.client.UpdateConfigurationBuilder');
goog.require('org.pepstock.charba.client.colors.GoogleChartColor');
goog.require('org.pepstock.charba.client.configuration.Axis');
goog.require('org.pepstock.charba.client.configuration.CartesianCategoryAxis');
goog.require('org.pepstock.charba.client.configuration.CartesianLinearAxis');
goog.require('org.pepstock.charba.client.data.Dataset');
goog.require('org.pepstock.charba.client.data.LineDataset');
goog.require('org.pepstock.charba.client.dom.IsCastable.$Overlay');
goog.require('org.pepstock.charba.client.dom.enums.CursorType');
goog.require('org.pepstock.charba.client.events.AxisClickEvent');
goog.require('org.pepstock.charba.client.events.DatasetSelectionEvent');
goog.require('org.pepstock.charba.client.events.TitleClickEvent');
goog.require('org.pepstock.charba.client.impl.plugins.ChartPointer');
goog.require('org.pepstock.charba.client.impl.plugins.ChartPointerOptions');
goog.require('org.pepstock.charba.client.impl.plugins.enums.PointerElement');
goog.require('org.pepstock.charba.showcase.j2cl.cases.commons.BaseComposite');
goog.require('org.pepstock.charba.showcase.j2cl.cases.commons.LogView');
goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.PointerLineCase.$1');
goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.PointerLineCase.$2');
goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.PointerLineCase.$3');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Casts');
goog.require('vmbootstrap.Primitives');

const PointerLineCase = goog.require('org.pepstock.charba.showcase.j2cl.cases.plugins.PointerLineCase$impl');
exports = PointerLineCase;

