# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Build
# 
# Runs only on push events on branch 'master'
# 
on:
  push:
    branches:
      - master

# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:
# 
# Workflow environment and steps
# 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Setup Java JDK
      # 
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      # 
      # Setup Maven
      # 
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      # 
      # Defines Charba lib in Maven
      # 
      - name: Adds Charba lib to Maven
        run: mvn install:install-file -Dfile=./lib/charba-5.8.jar -DgroupId=org.pepstock -DartifactId=charba -Dversion=5.8 -Dpackaging=jar --no-transfer-progress
      # 
      # Run the build of project by Maven
      # 
      - name: Build
        run: mvn --file pom.xml install --no-transfer-progress
