# *************************************
# Charba GitHub Actions build script 
# Copyright © 2020 pepstock.org      
# *************************************
# Workflow name
# 
name: Deploy from 'master' branch 
# 
# Runs only on new tag has been pushed
# and then publishes to gh-pages
# 
on:
  push:
    branches:
      - deploy

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# 
# Workflow environment and steps
# 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 
      # Checkout the repository content
      # 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone 
          fetch-depth: 0
      # 
      # Setup Java JDK
      # 
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      # 
      # Setup Maven
      # 
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3
      # 
      # Defines Charba lib in Maven
      # 
      - name: Adds Charba lib to Maven
        run: mvn install:install-file -Dfile=./lib/charba-5.6.jar -DgroupId=org.pepstock -DartifactId=charba -Dversion=5.6 -Dpackaging=jar  --no-transfer-progress
      # 
      # Run the build of project by Maven
      # 
      - name: Build
        run: mvn --file pom.xml install --no-transfer-progress
      # 
      # Removes sources from WAR
      # 
      - name: Remove JAVA sources
        run: ant remove
      # 
      # Removes .gitignore
      # 
      - name: Remove .gitignore 
        run: rm -f ./war/.gitignore
      # 
      # Deploy showcase to GitHub Pages
      # 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./war
          enable_jekyll: false
          keep_files: false
          full_commit_message: Deploy 'master' showcase to GitHub Pages