goog.module('org.pepstock.charba.client.colors.tiles.Shape');

goog.require('java.lang.Enum');
goog.require('nativebootstrap.Equality');
goog.require('nativebootstrap.Util');
goog.require('org.pepstock.charba.client.colors.tiles.BackSlashedLine');
goog.require('org.pepstock.charba.client.colors.tiles.Box');
goog.require('org.pepstock.charba.client.colors.tiles.Cross');
goog.require('org.pepstock.charba.client.colors.tiles.CrossDash');
goog.require('org.pepstock.charba.client.colors.tiles.Dash');
goog.require('org.pepstock.charba.client.colors.tiles.Diagonal');
goog.require('org.pepstock.charba.client.colors.tiles.Diamond');
goog.require('org.pepstock.charba.client.colors.tiles.DiamondBox');
goog.require('org.pepstock.charba.client.colors.tiles.Disc');
goog.require('org.pepstock.charba.client.colors.tiles.Dot');
goog.require('org.pepstock.charba.client.colors.tiles.DotDash');
goog.require('org.pepstock.charba.client.colors.tiles.DoubleDiagonal');
goog.require('org.pepstock.charba.client.colors.tiles.EmptyStar');
goog.require('org.pepstock.charba.client.colors.tiles.InvertedDiagonal');
goog.require('org.pepstock.charba.client.colors.tiles.InvertedDoubleDiagonal');
goog.require('org.pepstock.charba.client.colors.tiles.InvertedTriangle');
goog.require('org.pepstock.charba.client.colors.tiles.IsShape');
goog.require('org.pepstock.charba.client.colors.tiles.Line');
goog.require('org.pepstock.charba.client.colors.tiles.Plus');
goog.require('org.pepstock.charba.client.colors.tiles.Ring');
goog.require('org.pepstock.charba.client.colors.tiles.ShapeDrawer');
goog.require('org.pepstock.charba.client.colors.tiles.SlashedLine');
goog.require('org.pepstock.charba.client.colors.tiles.Solid');
goog.require('org.pepstock.charba.client.colors.tiles.Square');
goog.require('org.pepstock.charba.client.colors.tiles.Star');
goog.require('org.pepstock.charba.client.colors.tiles.Triangle');
goog.require('org.pepstock.charba.client.colors.tiles.VerticalLine');
goog.require('org.pepstock.charba.client.colors.tiles.VerticalZigZag');
goog.require('org.pepstock.charba.client.colors.tiles.Weave');
goog.require('org.pepstock.charba.client.colors.tiles.ZigZag');
goog.require('vmbootstrap.Arrays');
goog.require('vmbootstrap.Enums');

const Shape = goog.require('org.pepstock.charba.client.colors.tiles.Shape$impl');
exports = Shape;

